# Generated by Django 4.2.6 on 2023-10-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=50, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='контактный email')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'Клиент сервиса',
                'verbose_name_plural': 'Клиенты сервисов',
            },
        ),
        migrations.CreateModel(
            name='MailingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_mailing', models.CharField(choices=[('создана', 'создана'), ('запущена', 'запущена'), ('завершена', 'завершена')], max_length=10, verbose_name='статус рассылки')),
                ('time_mailing', models.DateTimeField(auto_now_add=True, verbose_name='время рассылки')),
                ('periodicity', models.CharField(choices=[('раз в день', 'раз в день'), ('раз в месяц', 'раз в месяц'), ('раз в неделю', 'раз в неделю')], max_length=15, verbose_name='переодичность')),
                ('client', models.ManyToManyField(to='mailing.clientservices', verbose_name='клиенты')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
