# Generated by Django 4.2.6 on 2023-10-11 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='контактный email')),
                ('surname', models.CharField(max_length=50, verbose_name='фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='отчество')),
                ('comment', models.TextField(max_length=200, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'Клиент сервиса',
                'verbose_name_plural': 'Клиенты сервисов',
            },
        ),
        migrations.CreateModel(
            name='MailingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_mailing', models.DateTimeField(auto_now_add=True, verbose_name='время рассылки')),
                ('status_mailing', models.CharField(choices=[('created', 'создана'), ('launched', 'запущена'), ('completed', 'завершена')], max_length=10, verbose_name='статус рассылки')),
                ('periodicity', models.CharField(choices=[('раз в день', 'Daily'), ('раз в месяц', 'Monthly'), ('раз в неделю', 'Weekly')], default='раз в день', max_length=15, verbose_name='переодичность')),
                ('client', models.ManyToManyField(to='mailing.clientservices')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_message', models.CharField(max_length=100, verbose_name='тема письма')),
                ('body_message', models.TextField(max_length=200, verbose_name='тело письма')),
                ('mailing_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingsetting')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='LogMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=150, verbose_name='статус попытки')),
                ('otvet', models.CharField(max_length=150, verbose_name='ответ почтового сервера, если он был.')),
                ('attempts', models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')),
                ('mailing_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingsetting')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
