# Generated by Django 4.2.6 on 2023-10-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservices',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='mailingsetting',
            name='periodicity',
            field=models.CharField(choices=[('раз в день', 'раз в день'), ('раз в месяц', 'раз в месяц'), ('раз в неделю', 'раз в неделю')], max_length=15, verbose_name='переодичность'),
        ),
        migrations.AlterField(
            model_name='mailingsetting',
            name='status_mailing',
            field=models.CharField(choices=[('создана', 'создана'), ('запущена', 'запущена'), ('завершена', 'завершена')], max_length=10, verbose_name='статус рассылки'),
        ),
    ]
