# Generated by Django 4.2.6 on 2023-10-29 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsetting',
            name='time_mailing',
            field=models.DateTimeField(verbose_name='время рассылки'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_message', models.CharField(max_length=100, verbose_name='тема письма')),
                ('body_message', models.TextField(max_length=200, verbose_name='тело письма')),
                ('mailing_setting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingsetting')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
