# Generated by Django 4.2.6 on 2023-10-29 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_message_mailing_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mailing_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingsetting', verbose_name='Рассылка'),
        ),
    ]
