# Generated by Django 4.2.6 on 2023-10-29 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_message_mailing_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OK', 'OK'), ('Fail', 'Fail')], max_length=150, verbose_name='статус попытки')),
                ('response_mail_server', models.CharField(max_length=150, verbose_name='ответ почтового сервера, если он был.')),
                ('attempts', models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.clientservices')),
                ('mailing_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingsetting')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
